site_name: sing-box
site_author: nekohasekai
repo_url: https://github.com/SagerNet/sing-box
repo_name: SagerNet/sing-box
copyright: Copyright &copy; 2022 nekohasekai
site_description: The universal proxy platform.
remote_branch: docs
edit_uri: ""
theme:
  name: material
  icon:
    logo: material/tools
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - header.autohide
nav:
  - Getting Started: index.md
  - Configuration:
      - configuration/index.md
      - Log: configuration/log.md
      - DNS:
          - configuration/dns/index.md
          - DNS Server: configuration/dns/server.md
          - DNS Rule: configuration/dns/rule.md
      - Inbound:
          - configuration/inbound/index.md
          - Direct: configuration/inbound/direct.md
          - Mixed: configuration/inbound/mixed.md
          - Socks: configuration/inbound/socks.md
          - HTTP: configuration/inbound/http.md
          - Shadowsocks: configuration/inbound/shadowsocks.md
          - VMess: configuration/inbound/vmess.md
          - Tun: configuration/inbound/tun.md
          - Redirect: configuration/inbound/redirect.md
          - TProxy: configuration/inbound/tproxy.md
      - Outbound:
          - configuration/outbound/index.md
          - Direct: configuration/outbound/direct.md
          - Block: configuration/outbound/block.md
          - Socks: configuration/outbound/socks.md
          - HTTP: configuration/outbound/http.md
          - Shadowsocks: configuration/outbound/shadowsocks.md
          - VMess: configuration/outbound/vmess.md
          - DNS: configuration/outbound/dns.md
          - Selector: configuration/outbound/selector.md
      - Route:
          - configuration/route/index.md
          - GeoIP: configuration/route/geoip.md
          - Geosite: configuration/route/geosite.md
          - Route Rule: configuration/route/rule.md
          - Protocol Sniff: configuration/route/sniff.md
      - Experimental: configuration/experimental.md
      - Shared:
          - TLS: configuration/shared/tls.md
          - Multiplex: configuration/shared/multiplex.md
  - Examples:
      - examples/index.md
      - Linux Server Install: examples/linux-server-install.md
      - Shadowsocks Server: examples/ss-server.md
      - Shadowsocks Client: examples/ss-client.md
      - Shadowsocks Tun: examples/ss-tun.md
      - DNS Hijack: examples/dns-hijack.md
  - Benchmark: benchmark.md
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SagerNet/sing-box
  generator: false
