site_name: sing-box
site_author: nekohasekai
repo_url: https://github.com/SagerNet/sing-box
repo_name: SagerNet/sing-box
copyright: Copyright &copy; 2022 nekohasekai
site_description: The universal proxy platform.
remote_branch: docs
edit_uri: ""
theme:
  name: material
  logo: assets/icon.svg
  favicon: assets/icon.svg
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    #    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - header.autohide
nav:
  - Getting Started:
      - index.md
      - Features: features.md
      - Support: support.md
      - Change Log: changelog.md
  - Installation:
      - From source: installation/from-source.md
      - Clients:
          - SFI:
              - installation/clients/sfi/index.md
  - Configuration:
      - configuration/index.md
      - Log:
          - configuration/log/index.md
      - DNS:
          - configuration/dns/index.md
          - DNS Server: configuration/dns/server.md
          - DNS Rule: configuration/dns/rule.md
      - NTP:
          - configuration/ntp/index.md
      - Route:
          - configuration/route/index.md
          - GeoIP: configuration/route/geoip.md
          - Geosite: configuration/route/geosite.md
          - IP Route Rule: configuration/route/ip-rule.md
          - Route Rule: configuration/route/rule.md
          - Protocol Sniff: configuration/route/sniff.md
      - Experimental:
          - configuration/experimental/index.md
      - Shared:
          - Listen Fields: configuration/shared/listen.md
          - Dial Fields: configuration/shared/dial.md
          - TLS: configuration/shared/tls.md
          - Multiplex: configuration/shared/multiplex.md
          - V2Ray Transport: configuration/shared/v2ray-transport.md
          - UDP over TCP: configuration/shared/udp-over-tcp.md
      - Inbound:
          - configuration/inbound/index.md
          - Direct: configuration/inbound/direct.md
          - Mixed: configuration/inbound/mixed.md
          - SOCKS: configuration/inbound/socks.md
          - HTTP: configuration/inbound/http.md
          - Shadowsocks: configuration/inbound/shadowsocks.md
          - VMess: configuration/inbound/vmess.md
          - Trojan: configuration/inbound/trojan.md
          - Naive: configuration/inbound/naive.md
          - Hysteria: configuration/inbound/hysteria.md
          - ShadowTLS: configuration/inbound/shadowtls.md
          - VLESS: configuration/inbound/vless.md
          - Tun: configuration/inbound/tun.md
          - Redirect: configuration/inbound/redirect.md
          - TProxy: configuration/inbound/tproxy.md
      - Outbound:
          - configuration/outbound/index.md
          - Direct: configuration/outbound/direct.md
          - Block: configuration/outbound/block.md
          - SOCKS: configuration/outbound/socks.md
          - HTTP: configuration/outbound/http.md
          - Shadowsocks: configuration/outbound/shadowsocks.md
          - VMess: configuration/outbound/vmess.md
          - Trojan: configuration/outbound/trojan.md
          - WireGuard: configuration/outbound/wireguard.md
          - Hysteria: configuration/outbound/hysteria.md
          - ShadowTLS: configuration/outbound/shadowtls.md
          - ShadowsocksR: configuration/outbound/shadowsocksr.md
          - VLESS: configuration/outbound/vless.md
          - Tor: configuration/outbound/tor.md
          - SSH: configuration/outbound/ssh.md
          - DNS: configuration/outbound/dns.md
          - Selector: configuration/outbound/selector.md
          - URLTest: configuration/outbound/urltest.md
  - FAQ:
      - faq/index.md
      - Known Issues: faq/known-issues.md
  - Examples:
      - examples/index.md
      - Linux Server Installation: examples/linux-server-installation.md
      - Tun: examples/tun.md
      - DNS Hijack: examples/dns-hijack.md
      - Shadowsocks: examples/shadowsocks.md
      - ShadowTLS: examples/shadowtls.md
      - Clash API: examples/clash-api.md
  - Contributing:
      - contributing/index.md
      - Developing:
          - Environment: contributing/environment.md
          - Sub projects: contributing/sub-projects.md
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SagerNet/sing-box
  generator: false
plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: false
        zh:
          name: 简体中文
      material_alternate: true
      nav_translations:
        zh:
          Getting Started: 开始
          Features: 特性
          Support: 支持
          Change Log: 更新日志

          Installation: 安装
          From source: 从源代码
          Clients: 客户端

          Configuration: 配置
          Log: 日志
          DNS Server: DNS 服务器
          DNS Rule: DNS 规则

          Route: 路由
          IP Route Rule: IP 路由规则
          Route Rule: 路由规则
          Protocol Sniff: 协议探测

          Experimental: 实验性

          Shared: 通用
          Listen Fields: 监听字段
          Dial Fields: 拨号字段
          Multiplex: 多路复用
          V2Ray Transport: V2Ray 传输层

          Inbound: 入站
          Outbound: 出站

          FAQ: 常见问题
          Known Issues: 已知问题
          Examples: 示例
          Linux Server Installation: Linux 服务器安装
          DNS Hijack: DNS 劫持